In [ ]:
# file_aggregator
import csv, os
import shutil
import pandas as pd
import numpy as np
# fileDir = R'C:\Users\akash\Documents\Testing'
# fileOutput = R'C:\Users\akash\Documents\match_scouting_test.csv'
# fileEndDir = R'C:\Users\akash\Documents\endDir'
fileDir = R'C:\Users\Aztechs Robotics\Documents\Match Scouting Data'
fileOutput = R'C:\Users\Aztechs Robotics\Documents\schema.csv'
fileOutput_agg = R'C:\Users\Aztechs Robotics\Documents\match_scouting_2025_agg.csv'
fileOutput_radar = R'C:\Users\Aztechs Robotics\Documents\match_scouting_2025_radar.csv'
fileOutput_comp = R'C:\Users\Aztechs Robotics\Documents\match_scouting_2025_comp.csv'
fileEndDir = R'C:\Users\Aztechs Robotics\Documents\Previously Aggregated Scouting Data'

fileTest = R'C:\Users\Aztechs Robotics\Documents\match_scouting_2025_test.csv'

accepted_comps = {'', 'uvm', 'mayhem', 'battlecry', 'bc', 'minuteman'}
uvm = {69, 95, 157, 166, 237, 348, 811, 839, 1058, 1073, 1512, 1729, 2262, 2370, 2423, 2523, 3323, 
       4311, 4572, 4909, 5494, 5687, 6691, 6933, 7913, 8421, 8544, 9096, 9101, 10066, 10108, 10138, 10647}
mayhem = {131, 157, 166, 190, 319, 501, 1073, 1119, 1153, 1721, 1729, 1735, 1768, 1922, 2342, 2648, 
          3623, 3467, 3597, 5813, 5962, 6324, 8046, 9443}
bc = {48, 78, 88, 126, 131, 138, 151, 157, 166, 175, 177, 190, 238, 319, 467, 501, 694, 1058, 1073, 1100, 1155, 1277,
      1474, 1591, 1729, 1735, 1740, 1757, 1768, 1796, 2053, 2079, 2084, 2262, 2265, 2342, 2370, 2423, 2713, 2791, 
      2876, 2877, 3182, 3467, 4041, 4048, 4311, 4575, 4909, 5422, 5687, 6324, 6328, 7153, 7407, 8085, 8544, 8567, 8708,
      8724, 9443, 9642, 10063, 10229}
minuteman = {157, 175, 190, 663, 1071, 1099, 1119, 1735, 1768, 2064, 3182, 3464, 3467, 3566, 3623, 4169, 4905, 4909, 
             5347, 5422, 5902, 5962, 6328, 6620, 8013, 8708, 9644, 9729, 10063, 10393}



competition = input("Which competition to select? (Leave blank for all)").lower()




with open(fileOutput, 'a') as output:
    for entry in os.listdir(fileDir):
        filePath = fileDir + '\\'+ entry
        with open(filePath, "r") as file:
            data = ""
            data = file.read()
            output.write(data + "\n")
            file.close()
        shutil.move(filePath, fileEndDir)
    output.close()

data = pd.read_csv(fileOutput)

data['Auto'] = data['Auto #Scored Coral L1']*3 + data['Auto #Scored Coral L2']*4 + data['Auto #Scored Coral L3']*6 + data['Auto #Scored Coral L4']*7 + data['Auto #Scored Barge'] *4 + data['Auto #Scored Processor'] * 6 + data['Left Starting Position'] * 3
data['TeleopCoral'] = data['TeleOp #Scored Coral L1']*2 + data['TeleOp #Scored Coral L2']*3 + data['TeleOp #Scored Coral L3']*4 + data['TeleOp #Scored Coral L4']*5
data['TeleopAlgae'] = data['TeleOp #Scored Barge'] * 4 + data['TeleOp #Scored Processor'] * 2
# renaming data
# E.X. [T#SL1] = TeleOp Number Scored Coral L1
# E.X. [T#SP] = TeleOp Number Scored Barge
if(True):
    data['T#SL1'] = data['TeleOp #Scored Coral L1']
    data['T#SL2'] = data['TeleOp #Scored Coral L2']
    data['T#SL3'] = data['TeleOp #Scored Coral L3']
    data['T#SL4'] = data['TeleOp #Scored Coral L4']
    data['T#SB'] = data['TeleOp #Scored Barge']
    data['T#SP'] = data['TeleOp #Scored Processor']
    data['A#SL1'] = data['Auto #Scored Coral L1']
    data['A#SL2'] = data['Auto #Scored Coral L2']
    data['A#SL3'] = data['Auto #Scored Coral L3']
    data['A#SL4'] = data['Auto #Scored Coral L4']
    data['A#SB'] = data['Auto #Scored Barge']
    data['A#SP'] = data['Auto #Scored Processor']
    

    data['T#AL1'] = data['TeleOp #Attempted Coral L1']
    data['T#AL2'] = data['TeleOp #Attempted Coral L2']
    data['T#AL3'] = data['TeleOp #Attempted Coral L3']
    data['T#AL4'] = data['TeleOp #Attempted Coral L4']
    data['T#AB'] = data['TeleOp #Attempted Barge']
    data['T#AP'] = data['TeleOp #Attempted Processor']
    data['A#AL1'] = data['Auto #Attempted Coral L1']
    data['A#AL2'] = data['Auto #Attempted Coral L2']
    data['A#AL3'] = data['Auto #Attempted Coral L3']
    data['A#AL4'] = data['Auto #Attempted Coral L4']
    data['A#AB'] = data['Auto #Attempted Barge']
    data['A#AP'] = data['Auto #Attempted Processor']
    
mapping = {
    "Park": 2,
    "Hang Deep": 12,
    "Hang Shallow": 6
}
data["Endgame"] = data["Park/Shallow/Deep"].map(mapping).fillna(0).astype(int)

if(competition == 'uvm'):
    df_comp = data[data['Team Number'].isin(uvm)]
    print("Only UVM teams")
elif(competition == 'mayhem'):
    df_comp = data[data['Team Number'].isin(mayhem)]
    print("Only Mayhem teams")
elif(competition == 'battlecry' or competition == 'bc'):
    df_comp = data[data['Team Number'].isin(bc)]
    bc_copy = [x for x in bc if x not in data['Team Number'].tolist()]
    bc_copy.sort()
    print(bc_copy)
    print("Only Battlecry Teams")
else:
    df_comp = data
    print("All teams")



# df_comp.drop(inplace=True, columns=[col for col in df_comp.columns if '#Attempted' in col]+[col for col in df_comp.columns if '#Scored' in col])


col_to_drop = "Competition Location"
value_to_drop = "Test"
data_exclude_test = df_comp[~df_comp[col_to_drop].str.contains(value_to_drop, na=False)]
data_exclude_test.to_csv(fileOutput_comp)

# Match sheet data field
ms_df = data_exclude_test.groupby("Team Number")[["Auto", "TeleopCoral", "TeleopAlgae", "Endgame"] + [col for col in data_exclude_test.columns if 'A#' in col] + [col for col in data_exclude_test.columns if 'T#' in col]].mean(numeric_only=True).reset_index()


ms_df['Auto Score'] = ms_df['Auto']
# ms_df['Auto Acc'] = (ms_df['A#SL1']+ms_df['A#SL2']+ms_df['A#SL3']+ms_df['A#SL4']+ms_df["A#SP"]+ms_df['A#SB'])/(ms_df['A#AL1']+ms_df['A#AL2']+ms_df['A#AL3']+ms_df['A#AL4']+ms_df["A#AP"]+ms_df['A#AB'])
ms_df['Auto Coral'] = ms_df['A#SL1']*3+ms_df['A#SL2']*4+ms_df['A#SL3']*6+ms_df['A#SL4']*7
ms_df['Auto Algae'] = ms_df["A#SP"]*2+ms_df['A#SB']*4

ms_df['Teleop Score'] = ms_df['TeleopCoral'] + ms_df['TeleopAlgae']
ms_df['L1'] = ms_df['T#SL1']*2
ms_df['L2'] = ms_df['T#SL2']*3
ms_df['L3'] = ms_df['T#SL3']*4
ms_df['L4'] = ms_df['T#SL4']*5
ms_df['Processor'] = ms_df['T#SP']*2
ms_df['Barge'] = ms_df['T#SB']*4

ms_df['Endgame Score'] = ms_df['Endgame']
ms_df['Total Score'] = ms_df['Auto']+ms_df['TeleopCoral']+ms_df['TeleopAlgae']+ms_df['Endgame']

ms_df['AutoNorm'] = ms_df['Auto'] / ms_df['Auto'].max()
ms_df['L1Norm'] = ms_df['T#SL1'] / ms_df['T#SL1'].max()
ms_df['L2Norm'] = ms_df['T#SL2'] / ms_df['T#SL2'].max()
ms_df['L3Norm'] = ms_df['T#SL3'] / ms_df['T#SL3'].max()
ms_df['L4Norm'] = ms_df['T#SL4'] / ms_df['T#SL4'].max()
ms_df['TeleopAlgaeNorm'] = ms_df['TeleopAlgae'] / ms_df['TeleopAlgae'].max()
ms_df['EndgameNorm'] = ms_df['Endgame'] / ms_df['Endgame'].max()

ms_df['Auto Coral Acc'] = (ms_df['A#SL1']+ms_df['A#SL2']+ms_df['A#SL3']+ms_df['A#SL4'])/(ms_df['A#AL1']+ms_df['A#AL2']+ms_df['A#AL3']+ms_df['A#AL4'])
ms_df['Auto Algae Acc'] = (ms_df["A#SP"]+ms_df['A#SB'])/(ms_df["A#AP"]+ms_df['A#AB'])
ms_df['L1 Acc']=ms_df['T#SL1']/ms_df['T#AL1']
ms_df['L2 Acc']=ms_df['T#SL2']/ms_df['T#AL2']
ms_df['L3 Acc']=ms_df['T#SL3']/ms_df['T#AL3']
ms_df['L4 Acc']=ms_df['T#SL4']/ms_df['T#AL4']
ms_df['Processor Acc'] = ms_df['T#SP']/ms_df['T#AP']
ms_df['Barge Acc'] = ms_df['T#SB']/ms_df['T#AB']

ms_df.drop(columns=["Auto", "TeleopCoral", "TeleopAlgae", "Endgame"] + [col for col in data_exclude_test.columns if 'A#' in col] + [col for col in data_exclude_test.columns if 'T#' in col], inplace=True)
ms_df.replace(np.inf, 0, inplace=True)
ms_df.to_csv(fileOutput_agg)


# Radar Sheet Data Field
radar_norm = data_exclude_test.groupby("Team Number")[["Auto", "TeleopAlgae", "Endgame", "T#SL1", "T#SL2", "T#SL3", 
                                                       "T#SL4"]].mean().reset_index()
radar_norm['AutoNorm'] = radar_norm['Auto'] / radar_norm['Auto'].max()
radar_norm['L1'] = radar_norm['T#SL1'] / radar_norm['T#SL1'].max()
radar_norm['L2'] = radar_norm['T#SL2'] / radar_norm['T#SL2'].max()
radar_norm['L3'] = radar_norm['T#SL3'] / radar_norm['T#SL3'].max()
radar_norm['L4'] = radar_norm['T#SL4'] / radar_norm['T#SL4'].max()
radar_norm['TeleopAlgaeNorm'] = radar_norm['TeleopAlgae'] / radar_norm['TeleopAlgae'].max()
radar_norm['EndgameNorm'] = radar_norm['Endgame'] / radar_norm['Endgame'].max()

radar_norm.drop(columns=["Auto", "TeleopAlgae", "Endgame", "T#SL1", "T#SL2", "T#SL3", "T#SL4"], inplace=True)

radar_norm = radar_norm[['Team Number', 'TeleopAlgaeNorm','L1','L2','L3','L4','AutoNorm','EndgameNorm']]

radar_norm.to_csv(fileOutput_radar)


print ("Teams: " + str(len(radar_norm)))
print("Process Finished")

# Run only to clear data

In [1]:
import csv, os
import shutil
import pandas as pd
import numpy as np

ranier_dir = "/mnt/home/ranier-gran/Documents/Robotics/Scouting2026/"
ranier_dir = ""
# leo_dir = "C:\Users\every\StudioProjects\Scouting2026\schemas"

In [2]:
schema_path = ranier_dir + "schemas/"
full_df = pd.read_excel(schema_path + "Schema.xlsx")
full_df

Empty DataFrame
Columns: [Competition, randomNum, Scout, TeamNum, TeamColor, MatchNum, PreloadedFuel, StartingPos, AutoScored, AutoAccuracy, AutoPassed, AutoHang, TeleopScored, TeleopAccuracy, TeleopPassed, HangStatus, HangTime, AccuracyPos, OverBump, UnderTrench, PlayedDefense, CollectedFuel, PassedFuel, DidNothing, Other, Defense, StopReason, Rank, CommentsCNC]
Index: []

[0 rows x 29 columns]

In [3]:
match_csv_path = ranier_dir + "matchData/"
processed_csv_path = ranier_dir + "processedData/"

# Run each time you add data to your match data folder

In [4]:
match_data_dir = os.listdir(match_csv_path)
match_data_dir

['match_scouting_NERD_1058_3.csv',
 'match_scouting_NERD_1058_7.csv',
 'match_scouting_NERD_1119_5.csv',
 'match_scouting_NERD_157_1.csv',
 'match_scouting_NERD_1757_6.csv',
 'match_scouting_NERD_1768_2.csv',
 'match_scouting_NERD_190_4.csv',
 'match_scouting_NERD_2079_7.csv',
 'match_scouting_NERD_246_2.csv',
 'match_scouting_NERD_246_6.csv',
 'match_scouting_NERD_2713_2.csv',
 'match_scouting_NERD_467_5.csv',
 'match_scouting_NERD_4909_3.csv',
 'match_scouting_NERD_4909_6.csv',
 'match_scouting_NERD_5962_2.csv',
 'match_scouting_NERD_6201_4.csv',
 'match_scouting_NERD_6328_1.csv',
 'match_scouting_NERD_78_5.csv',
 'match_scouting_NERD_8567_3.csv',
 'match_scouting_NERD_88_1.csv',
 'match_scouting_NERD_9998_5.csv',
 'match_scouting_NERD_9999_6.csv']

In [5]:
def process_match_sheet(full_df, match_csv_path, sheet_name):
    match_df = pd.read_csv(match_csv_path + sheet_name, header = None)
    match_df.drop(29, axis=1, inplace=True)
    match_df.columns = full_df.columns
    full_df = pd.concat([full_df, match_df], ignore_index = True)
    return full_df

In [6]:
for file_name in match_data_dir:
    full_df = process_match_sheet(full_df, match_csv_path, file_name)
    shutil.move(match_csv_path + file_name, processed_csv_path + file_name)
full_df

,Competition,randomNum,Scout,TeamNum,TeamColor,MatchNum,PreloadedFuel,StartingPos,AutoScored,AutoAccuracy,...,UnderTrench,PlayedDefense,CollectedFuel,PassedFuel,DidNothing,Other,Defense,StopReason,Rank,CommentsCNC
0,NERD,2,Liam,1058,Red,3,True,Position 3,5,75%,...,False,False,True,True,False,False,No Defense,Not stopped,Rank 1,NaN
1,NERD,2,Liam,1058,Red,7,True,Position 1,50,75%,...,False,False,True,True,False,False,Light Defense,Not stopped,Rank 1,NaN
2,NERD,2,Eli,1119,Blue,5,True,Position 3,10,75%,...,False,True,True,False,False,False,Light Defense,Not stopped,Rank 3,NaN
3,NERD,2,Liam,157,Red,1,True,Position 2,50%,50%,...,False,False,True,True,False,False,No Defense,Not stopped,Rank 3,NaN
4,NERD,2,Liam,1757,Red,6,True,Position 1,NaN,50%,...,False,False,True,True,False,False,No Defense,Not stopped,Rank 1,NaN
5,NERD,2,Lweo,1768,Blue,2,True,Position 1,100,75%,...,True,False,True,True,False,False,Light Defense,Not stopped,Rank 1,NaN
6,NERD,2,Cali,190,Red,4,True,Position 3,NaN,Less Than 10%,...,False,False,True,False,False,False,Heavy Defense,Not stopped,Rank 2,NaN
7,NERD,2,Cali,2079,Red,7,True,Position 3,20,More than 95%,...,True,False,True,True,False,False,Light Defense,Not stopped,Rank 3,NaN
8,NERD,2,Berkeley,246,Red,2,True,Position 2,1,Less Than 10%,...,True,True,False,True,False,False,Heavy Defense,Not stopped,Rank 3,NaN
9,NERD,2,Cali,246,Red,6,True,Position 2,3,25%,...,True,False,True,True,True,False,No Defense,Not stopped,Rank 3,NaN
10,NERD,2,Liam,2713,Red,2,True,Position 1,NaN,50%,...,False,False,True,False,False,False,No Defense,Not stopped,Rank 1,NaN
11,NERD,2,Berkeley,467,Red,5,True,Position 3,20,50%,...,False,False,True,False,False,False,Light Defense,Not stopped,Rank 2,NaN
12,NERD,2,Cali,4909,Red,3,True,Position 2,NaN,Less Than 10%,...,True,False,True,True,False,False,No Defense,Not stopped,Rank 3,NaN
13,NERD,2,Eli,4909,Blue,6,True,Position 1,NaN,Less Than 10%,...,False,False,False,False,True,False,No Defense,Died,Rank 3,wasn't moving most of the match
14,NERD,2,Cali,5962,Red,2,True,Position 3,25%,25%,...,False,False,True,True,False,False,Light Defense,Not stopped,Rank 2,NaN
15,NERD,2,Liam,6201,Red,4,True,Position 1,NaN,Less Than 10%,...,False,True,False,False,False,False,Light Defense,Not stopped,Rank 2,played defense
16,NERD,2,Dan,6328,Red,1,False,Position 3,66,75%,...,True,False,True,True,False,False,No Defense,Not stopped,Rank 1,NaN
17,NERD,2,Cali,78,Red,5,True,Position 1,185,More than 95%,...,True,False,True,True,False,False,No Defense,Not stopped,Rank 1,NaN
18,NERD,2,Berkeley,8567,Red,3,False,Position 2,0,Less Than 10%,...,False,False,False,True,False,False,No Defense,Physically Broke,Rank 3,NaN
19,NERD,2,Maria,88,Red,1,True,Position 1,65,75%,...,True,False,True,False,False,False,No Defense,Tipped,Rank 2,NaN
20,NERD,2,Liam,9998,Red,5,True,Position 2,NaN,50%,...,False,True,True,False,False,False,No Defense,Not stopped,Rank 3,played defense
21,NERD,2,Berkeley,9999,Red,6,True,Position 3,NaN,Less Than 10%,...,False,False,False,False,True,False,No Defense,Tipped,Rank 3,mjust a base not a robot

In [7]:
full_df_dummies = full_df.copy()
full_df_dummies['AutoAccuracyNum'] = full_df_dummies['AutoAccuracy'].str[-3:-1].astype(float)/100
full_df_dummies['TeleopAccuracyNum'] = full_df_dummies['TeleopAccuracy'].str[-3:-1].astype(float)/100
columns_to_encode = ['AutoHang','HangStatus','AccuracyPos','OverBump','UnderTrench','PlayedDefense','CollectedFuel','PassedFuel','DidNothing','Other','Defense','StopReason']
full_dummies_df = pd.get_dummies(full_df_dummies, columns=columns_to_encode)
print("\nEncoded DataFrame:")
full_dummies_df

Encoded DataFrame:

,Competition,randomNum,Scout,TeamNum,TeamColor,MatchNum,PreloadedFuel,StartingPos,AutoScored,AutoAccuracy,...,DidNothing_False,DidNothing_True,Other_False,Defense_Heavy Defense,Defense_Light Defense,Defense_No Defense,StopReason_Died,StopReason_Not stopped,StopReason_Physically Broke,StopReason_Tipped
0,NERD,2,Liam,1058,Red,3,True,Position 3,5,75%,...,True,False,True,False,False,True,False,True,False,False
1,NERD,2,Liam,1058,Red,7,True,Position 1,50,75%,...,True,False,True,False,True,False,False,True,False,False
2,NERD,2,Eli,1119,Blue,5,True,Position 3,10,75%,...,True,False,True,False,True,False,False,True,False,False
3,NERD,2,Liam,157,Red,1,True,Position 2,50%,50%,...,True,False,True,False,False,True,False,True,False,False
4,NERD,2,Liam,1757,Red,6,True,Position 1,NaN,50%,...,True,False,True,False,False,True,False,True,False,False
5,NERD,2,Lweo,1768,Blue,2,True,Position 1,100,75%,...,True,False,True,False,True,False,False,True,False,False
6,NERD,2,Cali,190,Red,4,True,Position 3,NaN,Less Than 10%,...,True,False,True,True,False,False,False,True,False,False
7,NERD,2,Cali,2079,Red,7,True,Position 3,20,More than 95%,...,True,False,True,False,True,False,False,True,False,False
8,NERD,2,Berkeley,246,Red,2,True,Position 2,1,Less Than 10%,...,True,False,True,True,False,False,False,True,False,False
9,NERD,2,Cali,246,Red,6,True,Position 2,3,25%,...,False,True,True,False,False,True,False,True,False,False
10,NERD,2,Liam,2713,Red,2,True,Position 1,NaN,50%,...,True,False,True,False,False,True,False,True,False,False
11,NERD,2,Berkeley,467,Red,5,True,Position 3,20,50%,...,True,False,True,False,True,False,False,True,False,False
12,NERD,2,Cali,4909,Red,3,True,Position 2,NaN,Less Than 10%,...,True,False,True,False,False,True,False,True,False,False
13,NERD,2,Eli,4909,Blue,6,True,Position 1,NaN,Less Than 10%,...,False,True,True,False,False,True,True,False,False,False
14,NERD,2,Cali,5962,Red,2,True,Position 3,25%,25%,...,True,False,True,False,True,False,False,True,False,False
15,NERD,2,Liam,6201,Red,4,True,Position 1,NaN,Less Than 10%,...,True,False,True,False,True,False,False,True,False,False
16,NERD,2,Dan,6328,Red,1,False,Position 3,66,75%,...,True,False,True,False,False,True,False,True,False,False
17,NERD,2,Cali,78,Red,5,True,Position 1,185,More than 95%,...,True,False,True,False,False,True,False,True,False,False
18,NERD,2,Berkeley,8567,Red,3,False,Position 2,0,Less Than 10%,...,True,False,True,False,False,True,False,False,True,False
19,NERD,2,Maria,88,Red,1,True,Position 1,65,75%,...,True,False,True,False,False,True,False,False,False,True
20,NERD,2,Liam,9998,Red,5,True,Position 2,NaN,50%,...,True,False,True,False,False,True,False,True,False,False
21,NERD,2,Berkeley,9999,Red,6,True,Position 3,NaN,Less Than 10%,...,False,True,True,False,False,True,False,False,False,True

In [8]:
full_dummies_df.to_csv("data_hub/match_data_hub.csv", index=False)

In [9]:
match_data_dir = os.listdir(match_csv_path)
match_data_dir

[]

In [10]:
competition_dict = {
    "UVM": {
        "Week": 4, 
        "Teams": [157, 190, 1100, 175, 75, 88, 6328],
    },
    "WPI": {
        "Week": 5,
        "Teams": [97, 157, 190, 237, 348, 467, 716, 999, 1027, 
                 1100, 1474, 1740, 1757, 1768, 2079, 2168, 2262,
                 2370, 3205, 3467, 3634, 4048, 4628, 5000, 5112,
                 5347, 5422, 5491, 5494, 6333, 6762, 7760, 8544, 
                 8567, 8724, 9644, 10254, 10393, 11483],
    },
    "Battlecry": {
        "Week": 12,
        "Teams": [48, 126, 131, 151, 157, 166, 173, 190, 238, 271, 
                 467, 516, 694, 1155, 1277, 1474, 1591, 1729, 1735, 
                 1768, 1922, 2262, 2265, 2342, 2370, 2423, 3461, 
                 4122, 4176, 4546, 4575, 5494, 5735, 5813, 6153, 
                 6731, 6933, 7153, 8085, 8544, 8567, 8708, 8724, 
                 9990, 10063, 10262, 10910, 11175],
    },
    "Minuteman": {
        "Week": 1,
        "Teams": [157, 175, 663, 1071, 1099, 1119, 1735, 1768,
                 2064, 3182, 3464, 3467, 3566, 3623, 4169, 4905,
                 4909, 5347, 5422, 5902, 5962, 6328, 6620, 8013, 
                 8708, 9644, 9729, 10063, 10393]
    },
    "NERD": {
        "Week": 17,
        "Teams": [78, 88, 157, 9997, 190, 246, 467, 1058, 1119, 1474,
                  1757, 1768, 2079, 2713, 4909, 9999, 5735, 5962, 9992,
                  6201, 9991, 6328, 9998, 6731, 9993, 8567, 8626, 9644, 10063]
    },
}
competition_dict

{'UVM': {'Week': 4, 'Teams': [157, 190, 1100, 175, 75, 88, 6328]},
 'WPI': {'Week': 5,
  'Teams': [97,
   157,
   190,
   237,
   348,
   467,
   716,
   999,
   1027,
   1100,
   1474,
   1740,
   1757,
   1768,
   2079,
   2168,
   2262,
   2370,
   3205,
   3467,
   3634,
   4048,
   4628,
   5000,
   5112,
   5347,
   5422,
   5491,
   5494,
   6333,
   6762,
   7760,
   8544,
   8567,
   8724,
   9644,
   10254,
   10393,
   11483]},
 'Battlecry': {'Week': 12,
  'Teams': [48,
   126,
   131,
   151,
   157,
   166,
   173,
   190,
   238,
   271,
   467,
   516,
   694,
   1155,
   1277,
   1474,
   1591,
   1729,
   1735,
   1768,
   1922,
   2262,
   2265,
   2342,
   2370,
   2423,
   3461,
   4122,
   4176,
   4546,
   4575,
   5494,
   5735,
   5813,
   6153,
   6731,
   6933,
   7153,
   8085,
   8544,
   8567,
   8708,
   8724,
   9990,
   10063,
   10262,
   10910,
   11175]},
 'Minuteman': {'Week': 1,
  'Teams': [157,
   175,
   663,
   1071,
   1099,
   1119,
   1735,
   1768,
   2064,
   3182,
   3464,
   3467,
   3566,
   3623,
   4169,
   4905,
   4909,
   5347,
   5422,
   5902,
   5962,
   6328,
   6620,
   8013,
   8708,
   9644,
   9729,
   10063,
   10393]},
 'NERD': {'Week': 17,
  'Teams': [78,
   88,
   157,
   9997,
   190,
   246,
   467,
   1058,
   1119,
   1474,
   1757,
   1768,
   2079,
   2713,
   4909,
   9999,
   5735,
   5962,
   9992,
   6201,
   9991,
   6328,
   9998,
   6731,
   9993,
   8567,
   8626,
   9644,
   10063]}}

In [11]:
competition_name = 'NERD'
competition_df = full_dummies_df[full_dummies_df['TeamNum'].isin(competition_dict[competition_name]['Teams'])]
competition_df

,Competition,randomNum,Scout,TeamNum,TeamColor,MatchNum,PreloadedFuel,StartingPos,AutoScored,AutoAccuracy,...,DidNothing_False,DidNothing_True,Other_False,Defense_Heavy Defense,Defense_Light Defense,Defense_No Defense,StopReason_Died,StopReason_Not stopped,StopReason_Physically Broke,StopReason_Tipped
0,NERD,2,Liam,1058,Red,3,True,Position 3,5,75%,...,True,False,True,False,False,True,False,True,False,False
1,NERD,2,Liam,1058,Red,7,True,Position 1,50,75%,...,True,False,True,False,True,False,False,True,False,False
2,NERD,2,Eli,1119,Blue,5,True,Position 3,10,75%,...,True,False,True,False,True,False,False,True,False,False
3,NERD,2,Liam,157,Red,1,True,Position 2,50%,50%,...,True,False,True,False,False,True,False,True,False,False
4,NERD,2,Liam,1757,Red,6,True,Position 1,NaN,50%,...,True,False,True,False,False,True,False,True,False,False
5,NERD,2,Lweo,1768,Blue,2,True,Position 1,100,75%,...,True,False,True,False,True,False,False,True,False,False
6,NERD,2,Cali,190,Red,4,True,Position 3,NaN,Less Than 10%,...,True,False,True,True,False,False,False,True,False,False
7,NERD,2,Cali,2079,Red,7,True,Position 3,20,More than 95%,...,True,False,True,False,True,False,False,True,False,False
8,NERD,2,Berkeley,246,Red,2,True,Position 2,1,Less Than 10%,...,True,False,True,True,False,False,False,True,False,False
9,NERD,2,Cali,246,Red,6,True,Position 2,3,25%,...,False,True,True,False,False,True,False,True,False,False
10,NERD,2,Liam,2713,Red,2,True,Position 1,NaN,50%,...,True,False,True,False,False,True,False,True,False,False
11,NERD,2,Berkeley,467,Red,5,True,Position 3,20,50%,...,True,False,True,False,True,False,False,True,False,False
12,NERD,2,Cali,4909,Red,3,True,Position 2,NaN,Less Than 10%,...,True,False,True,False,False,True,False,True,False,False
13,NERD,2,Eli,4909,Blue,6,True,Position 1,NaN,Less Than 10%,...,False,True,True,False,False,True,True,False,False,False
14,NERD,2,Cali,5962,Red,2,True,Position 3,25%,25%,...,True,False,True,False,True,False,False,True,False,False
15,NERD,2,Liam,6201,Red,4,True,Position 1,NaN,Less Than 10%,...,True,False,True,False,True,False,False,True,False,False
16,NERD,2,Dan,6328,Red,1,False,Position 3,66,75%,...,True,False,True,False,False,True,False,True,False,False
17,NERD,2,Cali,78,Red,5,True,Position 1,185,More than 95%,...,True,False,True,False,False,True,False,True,False,False
18,NERD,2,Berkeley,8567,Red,3,False,Position 2,0,Less Than 10%,...,True,False,True,False,False,True,False,False,True,False
19,NERD,2,Maria,88,Red,1,True,Position 1,65,75%,...,True,False,True,False,False,True,False,False,False,True
20,NERD,2,Liam,9998,Red,5,True,Position 2,NaN,50%,...,True,False,True,False,False,True,False,True,False,False
21,NERD,2,Berkeley,9999,Red,6,True,Position 3,NaN,Less Than 10%,...,False,True,True,False,False,True,False,False,False,True

In [12]:
competition_df.columns

Index(['Competition', 'randomNum', 'Scout', 'TeamNum', 'TeamColor', 'MatchNum',
       'PreloadedFuel', 'StartingPos', 'AutoScored', 'AutoAccuracy',
       'AutoPassed', 'TeleopScored', 'TeleopAccuracy', 'TeleopPassed',
       'HangTime', 'Rank', 'CommentsCNC', 'AutoAccuracyNum',
       'TeleopAccuracyNum', 'AutoHang_False', 'AccuracyPos_About the same',
       'AccuracyPos_Consistently bad accuracy', 'AccuracyPos_When unmoving',
       'OverBump_True', 'UnderTrench_False', 'UnderTrench_True',
       'PlayedDefense_False', 'PlayedDefense_True', 'CollectedFuel_False',
       'CollectedFuel_True', 'PassedFuel_False', 'PassedFuel_True',
       'DidNothing_False', 'DidNothing_True', 'Other_False',
       'Defense_Heavy Defense', 'Defense_Light Defense', 'Defense_No Defense',
       'StopReason_Died', 'StopReason_Not stopped',
       'StopReason_Physically Broke', 'StopReason_Tipped'],
      dtype='object')

In [13]:
for i, val in enumerate(competition_df['AutoScored']):
    print(competition_df.index[i])
    print(val)
# competition_df.drop(26, inplace = True)

0
5
1
50
2
10
3
50%
4
nan
5
100
6
nan
7
20
8
1
9
3
10
nan
11
20
12
nan
13
nan
14
25%
15
nan
16
66
17
185
18
0
19
65
20
nan
21
nan

In [14]:
for col in competition_df.columns:
    if col not in ['TeamNum','MatchNum','randomNum', 'PreloadedFuel', 'CommentsCNC']:
        try:
            competition_df[col] = competition_df[col].astype('float64') # Convert to float64
        except:
            print(f"Could not convert column '{col}' to float64")
if "HangStatus_Level 1" not in competition_df.columns:
    competition_df['HangStatus_Level 1'] = 0
if "HangStatus_Level 2" not in competition_df.columns:
    competition_df['HangStatus_Level 2'] = 0
if "HangStatus_Level 3" not in competition_df.columns:
    competition_df['HangStatus_Level 3'] = 0
if "AutoHang_True" not in competition_df.columns:
    competition_df['AutoHang_True'] = 0

Could not convert column 'Competition' to float64
Could not convert column 'Scout' to float64
Could not convert column 'TeamColor' to float64
Could not convert column 'StartingPos' to float64
Could not convert column 'AutoScored' to float64
Could not convert column 'AutoAccuracy' to float64
Could not convert column 'TeleopAccuracy' to float64
Could not convert column 'Rank' to float64

In [15]:
competition_df.to_csv(f"data_hub/{competition_name}_team_match_data.csv", index = False)

In [16]:
competition_aggregate = competition_df.groupby('TeamNum').mean(numeric_only=True).reset_index()
competition_aggregate['TeleopHangTotal'] = competition_aggregate['HangStatus_Level 1'] * 10 + competition_aggregate['HangStatus_Level 2'] * 20 + competition_aggregate['HangStatus_Level 3'] * 30
competition_aggregate['AutoHangTotal'] = competition_aggregate['AutoHang_True'] * 15
competition_aggregate['HangTotal'] = competition_aggregate['AutoHangTotal'] + competition_aggregate['TeleopHangTotal']
competition_aggregate['PassedTotal'] = competition_aggregate['AutoPassed'] + competition_aggregate['TeleopPassed']
competition_aggregate

,TeamNum,AutoPassed,TeleopScored,TeleopPassed,HangTime,AutoAccuracyNum,TeleopAccuracyNum,AutoHang_False,AccuracyPos_About the same,AccuracyPos_Consistently bad accuracy,...,StopReason_Physically Broke,StopReason_Tipped,HangStatus_Level 1,HangStatus_Level 2,HangStatus_Level 3,AutoHang_True,TeleopHangTotal,AutoHangTotal,HangTotal,PassedTotal
0,78,20.0,185.0,0.0,0.0,0.950,0.950,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20.0
1,88,30.0,5.0,10.0,0.0,0.750,0.500,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40.0
2,157,NaN,0.0,35.0,0.0,0.500,0.100,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3,190,NaN,35.0,0.0,0.0,0.100,0.500,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
4,246,NaN,13.5,20.0,0.0,0.175,0.300,1.0,0.5,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
5,467,NaN,55.0,25.0,0.0,0.500,0.250,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
6,1058,NaN,115.0,25.0,0.0,0.750,0.850,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
7,1119,NaN,10.0,10.0,0.0,0.750,0.750,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
8,1757,NaN,57.0,50.0,0.0,0.500,0.500,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
9,1768,NaN,270.0,120.0,0.0,0.750,0.750,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
10,2079,NaN,10.0,15.0,0.0,0.950,0.250,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
11,2713,NaN,15.0,0.0,0.0,0.500,0.250,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
12,4909,NaN,32.5,12.5,0.0,0.100,0.425,1.0,0.5,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
13,5962,NaN,14.0,15.0,0.0,0.250,0.250,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
14,6201,NaN,0.0,0.0,0.0,0.100,0.500,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
15,6328,NaN,323.0,57.0,0.0,0.750,0.750,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
16,8567,NaN,23.0,40.0,0.0,0.100,0.250,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
17,9998,NaN,0.0,25.0,0.0,0.500,0.500,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
18,9999,NaN,0.0,30.0,0.0,0.100,0.100,1.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN

In [17]:
competition_aggregate.columns

Index(['TeamNum', 'AutoPassed', 'TeleopScored', 'TeleopPassed', 'HangTime',
       'AutoAccuracyNum', 'TeleopAccuracyNum', 'AutoHang_False',
       'AccuracyPos_About the same', 'AccuracyPos_Consistently bad accuracy',
       'AccuracyPos_When unmoving', 'OverBump_True', 'UnderTrench_False',
       'UnderTrench_True', 'PlayedDefense_False', 'PlayedDefense_True',
       'CollectedFuel_False', 'CollectedFuel_True', 'PassedFuel_False',
       'PassedFuel_True', 'DidNothing_False', 'DidNothing_True', 'Other_False',
       'Defense_Heavy Defense', 'Defense_Light Defense', 'Defense_No Defense',
       'StopReason_Died', 'StopReason_Not stopped',
       'StopReason_Physically Broke', 'StopReason_Tipped',
       'HangStatus_Level 1', 'HangStatus_Level 2', 'HangStatus_Level 3',
       'AutoHang_True', 'TeleopHangTotal', 'AutoHangTotal', 'HangTotal',
       'PassedTotal'],
      dtype='object')

In [18]:
competition_aggregate.to_csv(f"data_hub/{competition_name}_team_aggregate_data.csv", index = False)

In [19]:
competition_norm = competition_aggregate[['TeamNum', 'AutoScored','AutoPassed','TeleopScored','TeleopPassed', 'PassedTotal', 'HangTotal']]
competition_norm['AutoScoredNorm'] = competition_norm['AutoScored'] / competition_norm['AutoScored'].max()
competition_norm['AutoPassedNorm'] = competition_norm['AutoPassed'] / competition_norm['AutoPassed'].max()
competition_norm['TeleopScoredNorm'] = competition_norm['TeleopScored'] / competition_norm['TeleopScored'].max()
competition_norm['TeleopPassedNorm'] = competition_norm['TeleopPassed'] / competition_norm['TeleopPassed'].max()
competition_norm['PassedTotalNorm'] = competition_norm['PassedTotal'] / competition_norm['PassedTotal'].max()
competition_norm['HangTotalNorm'] = competition_norm['HangTotal'] / competition_norm['HangTotal'].max()
competition_norm

KeyError: "['AutoScored'] not in index"

In [ ]:
competition_norm.to_csv(f"data_hub/{competition_name}_team_norm_data.csv", index = False)